openapi: 3.0.0
info:
  title: API Loja Virtual
  version: 0.0.1
tags:
  - usuarios
paths:
  /produtos:
    post:
      tags:
        - usuarios
      requestBody:
        content:
          application/json:
            schema:
           
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: 

  /usuarios/login
  /usuarios/renovar
components:
  schemas:
  securityschemes:
