openapi: 3.0.0
info:
  title: Pratica API
  description: Praticando a API
  version: 0.1.0 
servers:
  - url: http://localhost:3000
    description: Ambiente de Desenvolvimento
tags:
  name: produtos
paths:
  /produtos:
    get:
      tag: 
        - produtos
      responses: 
        200:
          description: Uma lista de produtos
          content:
             application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProdutos'
    post:
      tag:
        - produtos
      requestBody:
          description: Um JSON com dados do novo Produto
          required: true
          content:
            applicaton/json:
              schema:
                $ref: '#/components/schemas/Produto'
      responses:
        201:
          description: Produto Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        422:
          description: Nome e preço são obrigatórios  
  /produtos/{produtoId}:
    get:
      tag:
        - produtos
      parameters:
        in: path
        name: produtoId
        schema: integer
        required: true
        description: Id do produto a ser buscado
      responses:
      200:
        description: Um JSON com os dados do produto encontrado
        content:
          applicaton/json:
          schema:
            $ref: '#/components/schemas/Produto'
      404:
        description: Produto não encontrado  
    put:
      tag:
        - produtos
      parameters:
        in: path
        name: produtoId
        schema: integer
        required: true
        description: Id do produto a ser atualizado
      requestBody:
        description: Um JSON com dados do novo produto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
      200:
        description: Produto atualizado com sucesso
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      404:
        description: Produto não encontrado
      422:  
        description: Nome e preço são obrigatórios
    delete:
      tag:
        - produtos
      parameters:
        in: path
        name: produtoId
        required: true
        description: Id do produto a ser removido
      responses:
      204:
        description: Produto removido com sucesso
      404:  
        description: Produto não encontrado
components:
  schemas:
    ArrayOfProdutos:
      type: array
      items:
    Produto:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        preco:
          type: number